### ISSUE TITLE
Can't find clear examples of use of this class

### ISSUE THREAD

**Issue by kezenwa** [PhpGt/CssXPath#133]
Can't find clear examples of use of this class.

Please give more clear examples

**Comment by g105b** [comment]
Hey @kezenwa ,

Thanks for your message, and thank you for giving me a kick to add more documentation.

I've added some more information here: https://github.com/PhpGt/CssXPath/wiki

Please can you let me know if there is any particular example you're looking for, or something you don't understand? I'll do my best to add it to the wiki to help you and others in the future.

Thanks,
Greg.
