### ISSUE TITLE
Attribute selector without tag name doesn't work

### ISSUE THREAD

**Issue by g105b** [PhpGt/CssXPath#218]
HTML:

```html
<form>
  <button name="do" value="save">Save!</button>
</form>
```

PHP:

```php
$saveButton = $document->querySelector("form [name='do'][value='save']");
```

Exception raised: `Gt\Dom\Exception\XPathQueryException - Query is malformed: //form//[@value="save"]`

As a quick fix, I can change the query selector to: `form button[name='do'][value='save']`, and by explicitly mentioning the `button` is being selected, the problem goes away. 

I think the issue is within [the "attribute" part of the regex](https://github.com/PhpGt/CssXPath/blob/master/src/Translator.php#L15) on line 15. It should optionally match an element before it, outside of its named matching group.

**Comment by sk-pathak** [comment]
Hey! I would like to work on this

**Comment by AlexVCS** [comment]
Hi, I'd like to work on this but am having trouble finding what file it's in. I forked the repo but haven't found it anywhere. Any idea where it is?

**Comment by g105b** [comment]
Hi @AlexVCS, that's great. I'll happily help guide you to the correct part of the code.

This repository is incredibly simple in design as it only has one thing to do: translate the CSS string to an XPath string.

The whole translation is done within the [Translator class](https://github.com/PhpGt/CssXPath/blob/master/src/Translator.php), using [named Regular Expression groups](https://www.regular-expressions.info/named.html) to match and isolate each part of the CSS selector.

At the top of the class, the `const cssRegex` contains all the parts of different types of selector. This is where all the matching happens:

Each regular expression part is separated by the pipe (|) known as an [Alternation](https://www.regular-expressions.info/alternation.html). This is just so we can use a single Regular Expression, but so we can make sense of it by naming the different groups on different lines. 

For example, the first line `'(?P<star>\*)'` is made up of the following regex parts:

- In PHP, regular expressions are strings. The `'` surrounding it is just the string terminator.
- The whole thing is surrounded by parentheses, so that it becomes a [Capturing Group](https://www.regular-expressions.info/brackets.html)
- The `?P<star>` is the regex syntax to convert the group into a [Named Capturing Group]. The name in this case is called "star".
- The `\*` is the actual regular expression - to match a star, we simply want to match a single asterisk and nothing else.
- Here's an example of this star match in action: https://regex101.com/r/CDqJzK/1

Another example, on line 13 is `'|(\.(?P<class>[\w-]*))', which is made up of the following regex parts:

- Again, the whole thing is surrounded by the string terminator `'`
- Now we see the pipe, `|`, known as the [Alternation](https://www.regular-expressions.info/alternation.html), which allows this part of the regex to be combined with the preceding parts.
- The pattern we want to match on is surrounded by the outer parentheses `(`
- Then, we want to match on a single period `\.`, but the period is not actually part of the class name
- Then we open the named matching group for the "class" named group with `(?P<class>`
- The actual regex to match the class name is `[\w-]*` which means: any word character or hyphen, any number of times
- Then we close both capturing blocks: `))`
- Here's an example of this class match in action: https://regex101.com/r/ILvKqP/1

Following on from the large regex are the definitions of what syntax each attribute selector looks like: https://github.com/PhpGt/CssXPath/blob/master/src/Translator.php#L19-L24

The actual processing occurs when the `asXPath()` function is called, or when the class is cast to a string.

Inside the `convert(string $css)` function, the selector is [split into separate parts](https://github.com/PhpGt/CssXPath/blob/master/src/Translator.php#L45-L49), before each sub-string is processed individually by the `convertSingleSelector()` function.

It's done this way because luckily both XPath and CSS selectors are written from left to right, so we can build up the XPath selector accordingly.

I hope that gives you all the information you need, but if not I'll happily jump on a call with you or write up answers to any questions you have. I will do anything to try and find more enthusiastic collaborators!

Cheers - let me know how you get on.

**Comment by AlexVCS** [comment]
Thanks for all the info @g105b. I've read it and looked around a bit. Does this seem right:

`"|(\(P<element>?[\w-])*[(?P<attribute>[\w-]*)((?P<attribute_equals>[=~$*]+)(?P<attribute_value>(.+\[\]'?)|[^\]]+))*\])+"`

**Comment by g105b** [comment]
I think you're almost there. The solution is almost certainly to tweak the regex for the attribute selector, but there are two issues with your current solution: 

1) There's a syntax error, according to regex101.com where I test regexes. Apparently there's an extra closing parenthesis.
2) I think your solution is overcomplicating what could be a very simple solution... take a look at the issue in isolation here: https://regex101.com/r/VzFq18/1 They all make a full match, apart from the final line which isn't fully matched. So I think you can take the part of the regex that matches an element, and use that as an optional prefix to the attribute selector.

I hope that makes sense, good luck!

**Comment by g105b** [comment]
I've just revisited the project where I found this bug. For context, here's the code that's causing the issue:

```html
<cost-editor>
	<form method="post">
		<label>
			<span>Product</span>
			<select name="product" required data-bind:value="@name">
				<option></option>
				<option data-list data-bind:text="title" data-bind:value="id">Product</option>
			</select>
		</label>
		<label>
			<span>Description</span>
			<input name="description" data-bind:value="@name" />
		</label>
		<label>
			<span>Amount</span>
			<input name="amount" required type="number" step="0.01" data-bind:value="amount.value" />
		</label>
	
		<div class="actions">
			<button name="do" value="save">Save</button>
			<button name="do" value="delete">Delete</button>
		</div>
	</form>
</cost-editor>
```

```php
function go(DynamicPath $dynamicPath):void {
	$id = $dynamicPath->get("cost");

	if($id === "_new") {
		$saveButton = $document->querySelector("cost-editor [name='do'][value='save']");
	}
}
```

The error message: `Gt\Dom\Exception\XPathQueryException - Query is malformed: //cost-editor//[@value="save"] vendor/phpgt/dom/src/XPathResult.php:31
`.

I will try and create a failing unit test in this repository when I get some time on it, unless you can beat me to it.

**Comment by AlexVCS** [comment]
is this better?

`"(\([\w-])*[(?P<attribute>[\w-]*((?P<attribute_equals>[=~$*]+)(?P<attribute_value>(.+\[\]'?)|[^\]]+))*\]"`

**Comment by g105b** [comment]
Please use this test-bed on regex-101: https://regex101.com/r/vee7GV/1

The regex in the "REGULAR EXPRESSION" section is the current regex from the repository.

As you can see, there are some tests in the "TEST STRING" section. One per line, I've added some known CSS selectors, and the website highlights the different parts that are detected - then, in the right section "MATCH INFORMATION", you'll be able to see all the named attributes and their corresponding values.

The colour-coded matches:

![image](https://github.com/PhpGt/CssXPath/assets/358014/a6830342-01ce-4e64-9471-c35dab63c52f)

Their corresponding values: 

![image](https://github.com/PhpGt/CssXPath/assets/358014/0ba65adb-854e-4ad7-966a-0268949fa6f8)

You can see from the MATCH INFORMATION section, when looking at Match 2:

- Group `attribute` = `name`
- Group `attribute_value` = `password`

This is the important part that's used in the library.

I think the in question is that the last three selectors don't fully match. You can see that the word `input` isn't matched as part of the selector. Maybe I'm wrong, but I think this is certainly a symptom of the problem I described in this issue description.

I've just pasted your suggestion into https://regex101.com/r/JEfW4K/1 with the same examples.

See in the "Match Information" section - your regex is indeed matching all the examples now, including the ones with the "input" prefix, but we're losing the `attribute` and `attribute_value` parts of the match now.

Please let me know if you're following my descriptions, because regexes are hard enough, let alone talking about them across the internet to someone :D

**Comment by g105b** [comment]
Sure. In a nutshell, `[name='nickname']` is detecting the attribute `name` and attribute_value `nickname`, but when there's an element selector prefixed like `input[name='nickname']` the regex is not matching the entire element's selector. In your latest example, it matched the entire element's selector, but stopped matching the attribute's `name`.

I'm away for a couple of days but will pick this up when I'm back.

Good luck!

**Comment by g105b** [comment]
No problem - Regexes are a nightmare! And my explanations are probably not helping...

The Ps are required. `?P<attribute>` indicates to match the group called "attribute, `?P<attribute_equals>` matches "attribute_equals", etc.

I think your previous edit to the regex was almost there, but if you look at the "Match information" section of Regex 101, it shows that it is no longer successfully matching anything in the `?P<attribute>` section. It's still matching `attribute_equals` and `attribute_value` fine, but it's losing that information. Apart from that, I think it'll work.

**Comment by chrishow** [comment]
I'm confused. 

I added this test case, expecting it to fail, but it passes:

```php
public function testAttributeWithoutTagName() {
	$document = new DOMDocument("1.0", "UTF-8");
	$document->loadHTML('<cost-editor><button name="do" value="save">Save!</button></cost-editor>');
	$xpath = new DOMXPath($document);

	$selector = new Translator("cost-editor [name='do'][value='save']");
	self::assertEquals(
		1,
		$xpath->query($selector)->length
	);

	self::assertEquals(
		'button',
		$xpath->query($selector)->item(0)->tagName
	);
}
```
Am I doing something wrong here?

**Comment by g105b** [comment]
@chrishow How odd! Usually Github issues are a great way of segregating individual units of functionality, but it looks like this one has inadvertently been fixed by another release. I'll go back to the original project that triggered this to clarify...

**Comment by g105b** [comment]
I can confirm that this issue is resolved in a previous release. The project that I was using that I originally created this issue for is working perfectly with no issues.
