### ISSUE TITLE
Attribute names are currently matched in a case-sensitive manner. This is correct for XML, but not for HTML

### ISSUE THREAD

**Issue by chrishow** [PhpGt/CssXPath#220]
I have noticed that HTML attribute names are matched in a case-sensitive manner, for example:

Given a document with the contents `<div data-FOO='bar'>baz</div>`, the selector `"[data-foo='bar']"` does not match.

This is the correct behaviour for XML documents, which are case-sensitive everywhere, but not for HTML documents, where [tag names and attribute names are case-insensitive](https://www.w3.org/TR/2010/WD-html-markup-20101019/documents.html#case-insensitivity).

I've submitted a [draft PR](https://github.com/PhpGt/CssXPath/pull/219) with a trivial fix for this, but this will break matching in XML documents. 

Perhaps there should be an optional argument to the `Translator` constructor which specifies the document's DOMDocumentType? Or a HtmlTranslator subclass with the different behaviour? 

I'll be happy to contribute the code, but wanted to get opinions from the community. 

I should like to add that I'm very grateful for this excellent package!

**Comment by g105b** [comment]
Thank you for your kind message @chrishow 

I'm trying to build PHP.Gt packages to a high quality to perform web development tasks in the way that I like to work. I'm glad to hear you are getting value from the package too!

I think a subclass would make most sense, keeping it in the same style as [PHP.Gt/Dom](https://www.php.gt/dom) (which is very close to the W3C spec). Maybe we could change the `Translator` class to abstract, and then implement an `HTMLTranslator` and `XMLTranslator`? This will make the distinction obvious, but also allow future development to continue in a tidy and easy to maintain manner.

**Comment by g105b** [comment]
Implemented just now, and I'll make a release with the latest changes in, so projects like [PHP.Gt/Dom](https://www.PHP.Gt/Dom) can start to enjoy this functionality.
