### ISSUE TITLE
querySelector and attribute's value

### ISSUE THREAD

**Issue by dmitriy-krista** [PhpGt/CssXPath#37]
When specifying the value for an attribute in querySelector() method like **tag[attr='value']** , the method doesn't work as expected and returns null.

Example to reproduce the issue:

```
<?php

require "vendor/autoload.php";

$html = file_get_contents("https://github.com");
$document = new \Gt\Dom\HTMLDocument($html);

//will print "Enterprise"
echo $document->querySelector("nav > ul > li > a[data-ga-click]")->innerText . "\n";

//will throw PHP Notice: Trying to get property 'innerText' of non-object
echo $document->querySelector("nav > ul > li > a[data-ga-click='(Logged out) Header, go to Enterprise']")->innerText . "\n";

```
The expected behaviour is that the last line should print "Enterprise" 

If I try to run the exact querySelector call in my browser, it works correctly and both lines print "Enterprise":

`document.querySelector("nav > ul > li > a[data-ga-click]").innerText`

`document.querySelector("nav > ul > li > a[data-ga-click='(Logged out) Header, go to Enterprise']").innerText`

**Comment by g105b** [comment]
I have isolated the bug to the naive use of `explode` on commas to separate queries:

https://github.com/PhpGt/CssXPath/blob/57e9a9e40b9df2acaef1b9194d6f9451d50b9394/src/Translator.php#L32

**Comment by g105b** [comment]
Here is a test case I'm working on before implementing: https://regex101.com/r/xB7rQ7/224

Notice the last example doesn't work. If anyone could help me understand backreferences in this example, we can squish the bug and close this issue.

**Comment by g105b** [comment]
Works a treat now. I'll release this to the next version which will be adopted by the next version of Dom.

Have fun!
